// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkzgjqrfodjcqhvmabim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBremdqcXJmb2RqY3Fodm1hYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDM0NDgsImV4cCI6MjA2MDQ3OTQ0OH0.tt2AkubCh06HoeWwkFd0R7OgSEJMEmIcxhVqrNHVTnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);